[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
	-DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384   ; 16KB stack cho loop task (HMAC + JSON + MQTT publish trong callback)
lib_deps =
	knolleary/PubSubClient@^2.8
	adafruit/DHT sensor library@^1.4.6
	madhephaestus/ESP32Servo@^1.2.1
	bblanchon/ArduinoJson@^7.0.4
